name: Build #ismi opsiyonel

on:
    push:
        branches:
            - main

env:
  REGISTRY: ghcr.io #github container registry (key)
  REPO OWNER: ${{ github.repository_owner }}

jobs:
  build:
    strategy:
      matrix: #aynı işlemi birden fazla projeye uygulamak istiyorsak kullanırız
        image_name: ["order", "shipping", "inventory"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 #Elimizdeki projeye checkout eder

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "corretto"

      - name: Build
        working-directory: ${{ matrix.image_name }} #her her projede çalıştırması için
        run: |
          ./gradlew bootJar 
          mv build/libs/$(ls build/libs) app.jar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract image metadata for ${{ matrix.image.name }}
        id: meta
        uses: docker/metadata-action@v4 #docker için gerekli olan metadatayı çıkarıyor(tag, label vs.) sadece bizden image adı istiyor
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/${{ matrix.image_name }}

      - name: Build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile  #Dockerfile ın bulunduğu yer contexttir
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GH_TOKEN }}

